export const List = [
  {
    id: 1,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "science",
  },
  {
    id: 2,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "science",
  },
  {
    id: 3,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 4,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 5,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 6,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 7,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 8,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 9,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 10,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 11,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 12,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 13,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 14,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 15,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 16,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 17,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 18,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 19,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 20,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 21,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 22,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 23,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 24,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
  {
    id: 25,
    studentID: "22/01dl002",
    firstName: "adesare",
    lastName: "adegbagi",
    class: "ss2",
    department: "commercial",
  },
];
