// AceSmart Pricing & Subscription Plans Data

export const EDUCATOR_PLANS = [
  {
    id: "starter",
    name: "Starter Trial",
    badge: "Free Forever",
    tagline: "Essential tools for small tutoring groups and classroom pilots.",
    monthlyPrice: 0,
    termlyPrice: 0,
    popular: false,
    studentLimit: 50,
    examLimit: 5,
    features: [
      "Up to 50 active students",
      "5 published examinations / month",
      "Standard past question bank (5,000 Qs)",
      "Automated CBT grading & scoring",
      "Basic PDF result sheets",
      "Email support",
    ],
    limitations: [
      "No biometric face proctoring",
      "No Excel bulk roster import",
      "AceSmart watermark on result sheets",
    ],
    ctaText: "Current Plan",
    disabled: true,
  },
  {
    id: "pro",
    name: "Educator Pro",
    badge: "Most Popular",
    tagline: "Comprehensive testing suite for growing schools and standard academies.",
    monthlyPrice: 25000,
    termlyPrice: 65000, // Saves ₦10k vs 3 months
    popular: true,
    studentLimit: 300,
    examLimit: "Unlimited",
    features: [
      "Up to 300 active students",
      "Unlimited published examinations",
      "Full 50,000+ past questions (JAMB/WAEC)",
      "Automated ALOC question bank importer",
      "Excel (.xlsx) bulk student roster import",
      "Instant Excel & PDF master score sheets",
      "Anti-cheat proctoring & tab-switch detector",
      "Custom school crest on result transcripts",
      "Priority WhatsApp & phone support",
    ],
    limitations: [
      "Basic camera face capture (no AI matching)",
    ],
    ctaText: "Upgrade to Pro",
    disabled: false,
  },
  {
    id: "institution",
    name: "Institution & School ERP",
    badge: "All-in-One Suite",
    tagline: "Complete School Management System + AI CBT Proctored Examination Suite.",
    monthlyPrice: 60000,
    termlyPrice: 150000, // Saves ₦30k vs 3 months
    popular: false,
    studentLimit: 1000,
    examLimit: "Unlimited",
    features: [
      "Up to 1,000 active students (Unified Student Codes)",
      "All-in-One School Management System (SMS)",
      "Klacify-style Teacher QR Barcode Attendance Clock-In",
      "Student Classroom Daily Attendance & Roll Call",
      "Terminal Report Card Broadsheets (CBT Sync + Manual Scores)",
      "Termly School Fee Billing & Parent Online Payment Portal",
      "Debtor Defaulter Tracker with 1-Click Fee Reminders",
      "₦500 Terminal Result-Checker Paywall Token Engine",
      "Custom School Crest & White-Label Portal Branding",
      "Unlimited published examinations + AI Face Proctoring",
      "50,000+ past questions + Offline test room sync",
      "Dedicated account manager & priority phone support",
    ],
    limitations: [],
    ctaText: "Upgrade to Institution ERP",
    disabled: false,
  },
  {
    id: "enterprise",
    name: "Enterprise Multi-Campus",
    badge: "Custom Suite",
    tagline: "Custom-tailored deployment for state educational boards, dioceses & school groups.",
    monthlyPrice: 150000,
    termlyPrice: 400000,
    popular: false,
    studentLimit: "Unlimited",
    examLimit: "Unlimited",
    features: [
      "Unlimited student enrollments",
      "Multi-campus centralized governance",
      "Custom AI proctoring parameters",
      "On-premise / private cloud deployment option",
      "SLA 99.9% uptime guarantee",
      "Custom integration with school ERP/SIS",
      "Dedicated 24/7 technical engineer",
      "Staff onboarding and training workshops",
    ],
    limitations: [],
    ctaText: "Contact Enterprise",
    disabled: false,
  },
];

export const CANDIDATE_PASSES = [
  {
    id: "token-single",
    name: "Single Mock Token",
    price: 500,
    duration: "1 Simulated Exam",
    tagline: "Perfect for a quick test run before your official examination.",
    features: [
      "1 full-length simulated CBT exam (JAMB / WAEC format)",
      "Standard 4-subject UTME combination",
      "Real-time countdown timer & question palette",
      "Instant score breakdown and accuracy report",
      "Step-by-step answer explanations",
    ],
    ctaText: "Buy 1 Token (₦500)",
  },
  {
    id: "token-monthly",
    name: "Monthly Prep Pass",
    price: 2500,
    duration: "30 Days Unlimited",
    popular: true,
    tagline: "Intensive 30-day preparation with unrestricted practice tests.",
    features: [
      "Unlimited mock examinations for 30 days",
      "Access to all subjects and past year papers",
      "Weak topic diagnostic analytics",
      "JAMB score prediction engine",
      "Printable study performance certificate",
      "Priority server speed",
    ],
    ctaText: "Get 30-Day Pass (₦2,500)",
  },
  {
    id: "token-season",
    name: "UTME/WAEC Season Pass",
    price: 5000,
    duration: "90 Days (Full Exam Season)",
    popular: false,
    tagline: "Complete preparation package covering your entire exam season.",
    features: [
      "90 days unlimited access across UTME, WAEC, & Post-UTME",
      "Over 50,000 solved questions with diagrams",
      "Timed speed drills & topic-by-topic revisions",
      "National weekly mock challenge entry",
      "Live leaderboard & scholarship eligibility",
      "Offline downloadable revision PDFs",
    ],
    ctaText: "Get Season Pass (₦5,000)",
  },
];

export const INITIAL_INVOICES = [
  {
    id: "INV-2026-003",
    date: "2026-08-15",
    plan: "Educator Pro (Termly)",
    amount: "₦65,000.00",
    method: "Paystack Card (•••• 4242)",
    status: "Paid",
  },
  {
    id: "INV-2026-002",
    date: "2026-05-12",
    plan: "Educator Pro (Termly)",
    amount: "₦65,000.00",
    method: "Bank Transfer",
    status: "Paid",
  },
  {
    id: "INV-2026-001",
    date: "2026-01-10",
    plan: "Educator Pro (Monthly)",
    amount: "₦25,000.00",
    method: "Paystack Card (•••• 8910)",
    status: "Paid",
  },
];

export const FAQS = [
  {
    question: "What payment methods are supported?",
    answer: "We support all major Nigerian and international payment methods via Paystack and Flutterwave, including Mastercard, Visa, Verve cards, instant Bank Transfer, USSD codes (*737#, *919#, etc.), and Mobile Money.",
  },
  {
    question: "Can our school pay per term instead of monthly?",
    answer: "Yes! Our Termly billing cycle covers 3 full months and includes an automatic discount of up to 20% compared to paying month-to-month.",
  },
  {
    question: "What happens when our school exceeds the student enrollment limit?",
    answer: "You will receive an in-app notice when approaching your quota limit. You can seamlessly upgrade to the next tier at any time with prorated billing, without any interruption to ongoing examinations.",
  },
  {
    question: "Are examination results and student data preserved if we change plans?",
    answer: "Absolutely. All student records, past question banks, examination blueprints, and historical result sheets remain permanently securely backed up in our encrypted PostgreSQL database.",
  },
  {
    question: "Do you offer offline CBT testing solutions for schools without reliable internet?",
    answer: "Yes! Our Institution and Enterprise plans support our local offline sync server, allowing students to take tests over a local school LAN or Wi-Fi hotspot without internet access, and synchronizing scores to the cloud once connected.",
  },
];
