export const FakeStudents = [
  {
    id: 1,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 2,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 3,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 4,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 5,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 6,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 7,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 8,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 9,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
  {
    id: 10,
    firstName: "Kunle",
    lastName: "Afonja",
    role: "student",
    department: "science",
  },
];
